package codegen.generators

import com.maju.annotations.RepositoryProxy
import com.maju.entities.ConverterEntity
import com.maju.entities.MethodEntity
import com.maju.entities.ParameterEntity
import com.maju.entities.RepositoryEntity
import com.maju.generators.repository.proxy.RepositoryProxyGenerator
import com.maju.utils.toType
import com.squareup.kotlinpoet.BOOLEAN
import com.squareup.kotlinpoet.INT
import com.squareup.kotlinpoet.STRING
import com.squareup.kotlinpoet.metadata.KotlinPoetMetadataPreview
import core.IConverter
import core.util.AbstractRepositoryProxy
import core.util.IDTO
import core.util.IModel
import org.junit.Test
import kotlin.test.assertNotNull

data class Person(val name: String) : IModel

data class PersonDTO(val name: String) : IDTO

@RepositoryProxy(converter = PersonConverter::class)
interface PersonRepository {
    fun findByName(name: String): Person
    fun isDeleted(id: Long): Boolean
    fun save(person: Person): Person
    fun getAll(persons: List<Person>): List<Person>
}

class PersonRepositoryImpl : PersonRepository {
    override fun findByName(name: String): Person {
        return Person(name)
    }

    override fun isDeleted(id: Long): Boolean {
        return true
    }

    override fun save(person: Person): Person {
        return person
    }

    override fun getAll(persons: List<Person>): List<Person> {
        return persons
    }
}

class PersonConverter : IConverter<Person, PersonDTO> {
    override fun convertDTOToModel(dto: PersonDTO): Person {
        return Person(dto.name)
    }

    override fun convertModelToDTO(model: Person): PersonDTO {
        return PersonDTO(model.name)
    }
}


//Generated Class by KStruct Generator
class RepositoryProxyTest(
    private val personRepository: PersonRepository,
    override val converter: PersonConverter
) : AbstractRepositoryProxy<Person, PersonDTO>() {

    //Generated by KStruct Generator
    fun findByName(name: String): PersonDTO = toDTO { compute { personRepository.findByName(name) } }

    fun isDeleted(id: Long): Boolean = compute { personRepository.isDeleted(id) }!!

    fun save(person: PersonDTO) = toDTO { compute { personRepository.save(toModel { person }) } }

    fun getAll(persons: List<PersonDTO>) = toDTOs { compute { personRepository.getAll(toModels { persons }) } }
}


class PersonRepositoryProxyTestGeneratorTest {

    @Test
    fun test() {
        val repository = PersonRepositoryImpl()
        val personConverter = PersonConverter()
        val repositoryProxy = RepositoryProxyTest(repository, personConverter)
        val personDTO = repositoryProxy.findByName("Markus")
        println(personDTO)
        val test = repositoryProxy.save(personDTO)
        println(test)
        val getAll = repositoryProxy.getAll(listOf(personDTO))
        println(getAll)
        assertNotNull(getAll)
        assert(getAll.isNotEmpty())
    }

    @KotlinPoetMetadataPreview
    @Test
    fun generatedTest() {

        val dto = PersonDTO::class.toType()
        val model = Person::class.toType()

        val personRepositoryType = PersonRepository::class.toType()
        val personConverterType = PersonConverter::class.toType()

        val idParam = ParameterEntity(
            name = "id",
            type = INT.toType()
        )

        val nameParameter = ParameterEntity(
            name = "name",
            type = STRING.toType()
        )

        val testParameter = ParameterEntity(
            name = "test",
            type = STRING.toType()
        )

        val personParam = ParameterEntity(
            name = "person",
            type = dto
        )

        val findByNameMethod = MethodEntity(
            "findByName",
            listOf(nameParameter, testParameter),
            dto
        )

        val saveMethod = MethodEntity(
            name = "save",
            listOf(personParam),
            dto
        )

        val deleteMethod = MethodEntity(
            name = "deleteById",
            parameters = listOf(idParam),
            returnType = BOOLEAN.toType()
        )


        val repositoryProxyEntity = RepositoryEntity(
            modelClass = model,
            dtoClass = dto,
            type = personRepositoryType,
            methods = listOf(findByNameMethod, saveMethod, deleteMethod),
            converter = ConverterEntity(personConverterType),
            name = "PersonRepositoryProxy"
        )

        val repositoryProxyGenerator = RepositoryProxyGenerator("com.test", repositoryProxyEntity)


        val fileSpec = repositoryProxyGenerator.generate()
        println(fileSpec)

    }


}
